pipeline {
    agent any

    stages {
        stage('Checkout & Clean') {
            steps {
                echo '=== Étape 1 : Nettoyage ==='
                cleanWs()
            }
        }

        stage('Build & Test') {
            steps {
                echo '=== Étape 2 : Installation et vérification du projet React/Vite ==='
                // Commande batch Windows pour projet Node.js / Vite
                bat 'npm run build'
            }
        }
    }
}